#!/bin/bash

# we run without proper shell, therefore node may not be on the PATH - try to find it
if [ -x "/usr/local/bin/node" ]; then
    NODE="/usr/local/bin/node"
else
    NODE="node"
fi

BASEDIR=$(dirname $0)
SCRIPT="$NODE $BASEDIR/init.js"
RUNNING_PID="$BASEDIR/running.pid"

start() {
    if [ -f "$RUNNING_PID" ] && ps -p $(cat $RUNNING_PID) > /dev/null; then
        echo $SCRIPT already started
        return 1
    fi
    echo Starting $SCRIPT
    # background task may not log to the console, as it will prevent disconnect
    $SCRIPT > /dev/null 2> /dev/null &
    echo $! > $RUNNING_PID
    echo $SCRIPT started
}
 
stop() {
    if [ ! -f "$RUNNING_PID" ] || ! ps -p $(cat $RUNNING_PID) > /dev/null; then
        echo $SCRIPT is not running
        rm $RUNNING_PID > /dev/null
        return 1
    fi
    echo Stopping $SCRIPT
    kill -15 $(cat "$RUNNING_PID") && rm -f "$RUNNING_PID"
    echo $SCRIPT stopped
}
case $1 in
    start) start
    ;;
    stop) stop
    ;;
esac